<img src="http://www.ceic.org.ar/spanish/img/siisa-logo.jpg" align='right'>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
print(np.__version__)
print(pd.__version__)
#from sklearn.datasets import load_digits
#digits = load_digits()
#print(digits.DESCR)

1.16.3
0.24.2
.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each block. This generates
an input matrix of 8x8 where each element is an integer in the range
0..16. This reduces dimensionality and gives invariance to small
distortions.

For info on NIST preprocessing routines, see M. D. Garris, J. L. Blue, G.
T. Candela, D. L. Dimmick, J. Geist, P. J. Grother, S. A. Janet, and C.
L. Wilson, NIST Form-Based Handprint Recognition System, NISTIR 5469,
1994.

.. topic:: References

  - C. Kaynak (1995) Methods of Combining Multiple Classifiers and Their
    Applications to Handwritten Digit Recognition, MSc Thesis, Institute of
    Graduate Studies in Science and Engineering, Bogazici University.
  - E. Alpaydin, C. Kaynak (1998) Cascading Classifiers, Kybernetika.
  - Ken Tang and Ponnuthurai N. Suganthan and Xi Yao and A. Kai Qin.
    Linear dimensionalityreduction using relevance weighted LDA. School of
    Electrical and Electronic Engineering Nanyang Technological University.
    2005.
  - Claudio Gentile. A New Approximate Maximal Margin Classification
    Algorithm. NIPS. 2000.

In [2]:
df= pd.read_csv("Export-Politica3-20190301-20190331.csv")

C:\Users\elias\Programs\anaconda3\envs\siisa\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (41) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [18]:
df[:5][:]

,executionId,executionDate,executionDateTime,policyId,policyVersion,decisionResult,apellidoNombre,nroDoc,sexo,apellidoNombreSubstring,...,veraz_observacionesMontoCerrada1m,veraz_observacionesMontoCerrada24m,veraz_peorSituacionBureau4m,veraz_peorSituacionBureau5a12m,veraz_peorStatus12,veraz_peorStatusActual,veraz_poblacion,veraz_score,veraz_validado,Unnamed: 136
0,1715351,01/03/2019,00:00,3,36,RECHAZA|Perfil: Score SIISA no es mayor 300 |||,Gigena Juan marcelo,40655982,Masculino,gigena,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1715354,01/03/2019,00:03,3,36,RECHAZA|Perfil: Siisa_Veraz insuficiente 0|||,Lidia Teresa,31525318,Femenino,lidia,...,0.0,0.0,-,-,1.0,1.0,ok,196.0,True,NaN
2,1715355,01/03/2019,00:04,3,36,RECHAZA|Perfil: Score SIISA no es mayor 300 |||,Juan Francisco,37566775,Masculino,juan f,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1715356,01/03/2019,00:05,3,36,RECHAZA|Perfil:no trabaja en relación de depen...,Noelia,40163245,Femenino,noelia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1715357,01/03/2019,00:05,3,36,RECHAZA|Perfil: tiene al menos una situación m...,Rivero ariel orlando,25691534,Masculino,rivero,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN