In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

C:\Users\elias\Programs\anaconda3\envs\siisa\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\elias\Programs\anaconda3\envs\siisa\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\elias\Programs\anaconda3\envs\siisa\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\elias\Programs\anaconda3\envs\siisa\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
C:\Users\elias\Programs\anaconda3\envs\siisa\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [4]:
df=pd.read_csv('ej.cvs')

In [5]:
df.head()

,executionId,executionDate,executionDateTime,policyId,policyVersion,decisionResult,antiguedad_laboral,ApellidoNombre,Empleador,gastos_extracto,...,veraz_peorSituacionBureau712m,veraz_peorSituacionBureauActual,veraz_peorStatus12,veraz_peorStatusActual,veraz_poblacion,veraz_score,veraz_validado,ZonaFinal,ZonaNosis,ZonaSiisa
0,2016143,20/05/2019,00:01,1,213,Rechaza por info SIISA: Tiene al menos un cheq...,0,Turcoman Hugo,,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016145,20/05/2019,00:04,1,213,Rechaza: ingreso_F insuficiente,0,Scatto Carlos,,0,...,NaN,*,0.0,0.0,th,421.0,False,2.0,2.0,1.0
2,2016147,20/05/2019,00:05,1,213,Rechaza por info NOSIS: Tiene al menos una Sit...,0,Lucero Ismael,,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016149,20/05/2019,00:07,1,213,pide info extra,0,Musso Cyntia,,0,...,NaN,-,0.0,0.0,ok,490.0,False,2.0,2.0,1.0
4,2016150,20/05/2019,00:09,1,213,Rechaza: ingreso_F insuficiente,0,Arriagada Natalia,,0,...,NaN,-,0.0,0.0,ok,452.0,False,1.0,1.0,2.0

In [ ]:
siisa_scorePoblacion